Proyecto_1/Salud_Para_Tu_Sonriza/Controllers/PacientesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LogicaOdontologia.DTO;
using LogicaOdontologia.Session;
namespace Salud_Para_Tu_Sonriza.Controllers
{
    public class PacientesController : Controller
    {
        public IActionResult InsertarPacientes()
        {
            return View();
        }
        public IActionResult GuardarPacientes()
        {
            try
            {
                PacienteDTO _pacientesdto = new PacienteDTO();
                _pacientesdto.Nombre_Completo = Request.Form["txtNombre"].ToString();
                _pacientesdto.DPI = Convert.ToInt64(Request.Form["txtDPI"].ToString());
                _pacientesdto.Edad = Convert.ToInt32(Request.Form["txtEdad"].ToString());
                _pacientesdto.TelefonoContacto = Convert.ToInt64(Request.Form["txtTelefono"].ToString());
                _pacientesdto.Fecha_ultima_consulta = Convert.ToDateTime(Request.Form["dtpFechaUltima"].ToString());
                _pacientesdto.Fecha_proxima_consulta = Request.Form["dtpFechaProxima"].ToString() == string.Empty ? DateTime.MinValue.Date : Convert.ToDateTime(Request.Form["dtpFechaProxima"].ToString());
                string UltimoDiagnostico = Request.Form["txtultimoDiagnostico"].ToString();
                string Tratamiento = Request.Form["txtultimoDiagnostico"].ToString();
                if (UltimoDiagnostico != string.Empty || Tratamiento != UltimoDiagnostico)
                {
                    _pacientesdto.Descripciones_Tratamiento.Add(new DescripcionTratamientoDTO { Descripcion_Ultimo_Diagonisto = UltimoDiagnostico, Tratamiento_en_curso = Tratamiento });
                }
                if (_pacientesdto.Fecha_proxima_consulta.Value.Date != DateTime.MinValue.Date)
                {

                    List<PacienteDTO> Lista = (new GestorPacientes()).ListarPacientes();
                    var Element = from x in Lista where (x.Fecha_proxima_consulta == _pacientesdto.Fecha_proxima_consulta.Value.Date) select (x.Fecha_proxima_consulta);
                    if (Element.Count() < 8)
                    {
                        ViewData["Mensaje"] = "El paciente con DPI " + _pacientesdto.DPI.ToString() + " Registrado exitosamente";
                        (new GestorPacientes()).GuardarPacientes(_pacientesdto);
                    }
                    else
                    {
                        throw (new Exception("La fecha seleccionada ya tiene el limite de agendados"));
                     
                    }
                }
                ViewData["Mensaje"] = "El paciente con DPI " + _pacientesdto.DPI.ToString() + " Registrado exitosamente";
                (new GestorPacientes()).GuardarPacientes(_pacientesdto);

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View("../Home/Error");
            }
            return View();
        }
        public bool ContienePalabra(string Filtro, PacienteDTO data)
        {

            if (data.Descripciones_Tratamiento.Find(x => x.Tratamiento_en_curso.ToLower().Contains(Filtro.ToLower()) || x.Descripcion_Ultimo_Diagonisto.Contains(Filtro.ToLower())) != null)
            {
                return true;
            }
            return false;
        }
        public bool NoContienePalabra(PacienteDTO data)
        {

            if (data.Descripciones_Tratamiento.Find(x => x.Tratamiento_en_curso.ToLower().Contains("Ortodoncia".ToLower()) || x.Descripcion_Ultimo_Diagonisto.Contains("Ortodoncia".ToLower()) || x.Tratamiento_en_curso.ToLower().Contains("Caries".ToLower()) || x.Descripcion_Ultimo_Diagonisto.Contains("Caries".ToLower())) != null)
            {
                return true;
            }
            return false;
        }
        [HttpGet]
        public IActionResult ListarPacientes(string Tipo_Lista)
        {
            try
            {
                GestorPacientes gestorPacientes = new GestorPacientes();
                List<PacienteDTO> LISTAPACIENTES = new List<PacienteDTO>();
                LISTAPACIENTES = gestorPacientes.ListarPacientes();
                switch (Tipo_Lista)
                {
                    case "Lipieza Dental":
                        {
                            var Filtro = from x in LISTAPACIENTES where (x.Descripciones_Tratamiento.Count == 0 && Math.Abs((DateTime.Now.Month - x.Fecha_ultima_consulta.Month) + 12 * (DateTime.Now.Year - x.Fecha_ultima_consulta.Year)) >= 6) select (x);
                            ViewData["ListaPacientes"] = Filtro.ToList();
                            break;
                        }
                    case "Seguimiento Ortodoncia":
                        {
                            var Filtro = from x in LISTAPACIENTES where (ContienePalabra("Ortodoncia", x) && Math.Abs((DateTime.Now.Month - x.Fecha_ultima_consulta.Month) + 12 * (DateTime.Now.Year - x.Fecha_ultima_consulta.Year)) >= 2) select (x);
                            ViewData["ListaPacientes"] = Filtro.ToList();
                            break;
                        }
                    case "Lipieza Caries":
                        {
                            var Filtro = from x in LISTAPACIENTES where (ContienePalabra("Caries", x) && Math.Abs((DateTime.Now.Month - x.Fecha_ultima_consulta.Month) + 12 * (DateTime.Now.Year - x.Fecha_ultima_consulta.Year)) >= 4) select (x);
                            ViewData["ListaPacientes"] = Filtro.ToList();
                            break;
                        }
                    case "Tratamiento Especifico":
                        {
                            var Filtro = from x in LISTAPACIENTES where (!NoContienePalabra(x) && Math.Abs((DateTime.Now.Month - x.Fecha_ultima_consulta.Month) + 12 * (DateTime.Now.Year - x.Fecha_ultima_consulta.Year)) >= 6 && x.Descripciones_Tratamiento.Count > 0) select (x);
                            ViewData["ListaPacientes"] = Filtro.ToList();
                            break;
                        }
                    default:
                        {
                            ViewData["ListaPacientes"] = LISTAPACIENTES;
                            break;
                        }
                }

                return View();
            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View("../Home/Error");
            }

        }
        public IActionResult BuscarPaciente()
        {
            string Filtro = Request.Form["txtFiltro"].ToString();
            GestorPacientes gestorPacientes = new GestorPacientes();
            PacienteDTO Element = gestorPacientes.BuscarPaciente(Filtro);

            if (Element == null) { ViewData["Paciente"] = null; } else { ViewData["Paciente"] = Element; }

            return View();
        }
        public IActionResult ActualizarPaciente()
        {
            string TipoEnvio = Request.Form["TipoEnvio"].ToString();
            switch (TipoEnvio)
            {
                case "FormularioActualizacion":
                    {
                        GestorPacientes gestorPacientes = new GestorPacientes();
                        string DPI = (Request.Form["txtDPI"].ToString());
                        PacienteDTO pacienteDTO = gestorPacientes.BuscarPaciente(DPI);
                        ViewData["DataPaciente"] = pacienteDTO;
                        return View("./InsertarPacientes");
                        break;
                    }
                case "FormularioProceso":
                    {
                        GestorPacientes gestorPacientes = new GestorPacientes();
                        string DPI = (Request.Form["txtDPI"].ToString());
                        PacienteDTO pacienteDTO = gestorPacientes.BuscarPaciente(DPI);
                        DescripcionTratamientoDTO Descripcion = new DescripcionTratamientoDTO();
                        Descripcion.Descripcion_Ultimo_Diagonisto = Request.Form["txtDiagnostico"].ToString();
                        Descripcion.FechaDiagnostico = DateTime.Today;
                        Descripcion.Tratamiento_en_curso = Request.Form["txtTratamiento"].ToString();
                        pacienteDTO.Descripciones_Tratamiento.Add(Descripcion);
                        gestorPacientes.GuardarPacientes(pacienteDTO);
                        ViewData["Mensaje"] = "El paciente con DPI " + pacienteDTO.DPI.ToString() + " Actualizado exitosamente";
                        return View("./GuardarPacientes");
                        break;
                    }
                case "ReagendarCita":{
                        GestorPacientes gestorPaciente = new GestorPacientes();
                        string DPI = (Request.Form["txtDPI"].ToString());
                        PacienteDTO paciente = gestorPaciente.BuscarPaciente(DPI);
                        paciente.Fecha_proxima_consulta = Convert.ToDateTime(Request.Form["txtFechaNueva"].ToString()).Date;
                        if (gestorPaciente.CambiarFecha(paciente))
                        {

                            ViewData["Mensaje"] = "La fecha de la cita siguiente del paciente con DPI " + paciente.DPI.ToString() + "fue Actualizado exitosamente";
                            return View("./GuardarPacientes");
                        }
                        else {
                            ViewBag.Message = "El dia con la fecha seleccionada ya esta llena";
                            return View("../Home/Error");

                        }

                        break;
                    }
            
        }
            return View();


    }
        [HttpGet]
        public IActionResult EliminarPaciente(Int64 DPI)
    {
        try
        {
            GestorPacientes gestorPacientes = new GestorPacientes();
            gestorPacientes.EliminarPaciente(DPI);

Proyecto_1/Salud_Para_Tu_Sonriza/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="~/Images/brillante.ico" />
    <title>@ViewData["Title"] - Salud para tu sonrisa</title>
    <link rel="stylesheet" href="~/lib/node_modules/normalize.css/normalize.css" />
    <link rel="stylesheet" href="~/lib/node_modules/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/node_modules/fortawesome/fontawesome-free/css/all.min.css" />
</head>
<body>
    <header class="bordesNav">
        <nav class="navbar  navbar-light bg-primary fixed-top">
            <div class="container-fluid bordesNav">
                <img src="~/Images/brillante.png" /> Salud para tu sonrisa
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel"><img src="~/Images/brillante.png" /> Salud para tu sonrisa</h5>
                        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <i class="fa-solid fa-house-user px-2"></i><a class="nav-link active" aria-current="page" asp-controller="home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <i class="fa-solid fa-shield px-2"></i> <a class="nav-link" asp-controller="home" asp-action="Privacy">Derechos de autor</a>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Pacientes
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                                    <li><i class="fa-solid fa-plus px-2"></i><a class="dropdown-item" asp-controller="Pacientes" asp-action="InsertarPacientes">Insertar Pacientes</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><i class="fa-solid fa-list px-2"></i><a class="dropdown-item" asp-controller="Pacientes" asp-action="ListarPacientes" asp-route-Tipo_Lista="ListaCompleta"> Listar Pacientes</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <i class="fa-solid fa-download px-2"></i><a class="nav-link" asp-controller="Pacientes" asp-action="DescargarLog">Descargar el log del arbol</a>
                            </li>
                        </ul>
                        <form class="d-flex" asp-controller="Pacientes" asp-action="BuscarPaciente">
                            <input class="form-control me-2" id="txtFiltro" name="txtFiltro" type="search" placeholder="Ingrese el DPI o el nombre del paciente que va a buscar" aria-label="Search">
                            <button type="submit" class="btn btn-outline-success">Buscar Paciente</button>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container margenNav">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer border-top  text-center text-white">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
            <!-- Section: Social media -->
            <section class="mb-4">
                <!-- Facebook -->
                <a class="btn btn-primary btn-floating m-1"
                   style="background-color: #3b5998;"
                   href="https://www.facebook.com/solsisgt"
                   role="button">
                    <i class="fab fa-facebook-f"></i>
                </a>


                <!-- Google -->
                <a class="btn btn-primary btn-floating m-1"
                   style="background-color: #dd4b39; "
                   href="mailto:solsis502.gt@gmail.com"
                   role="button">
                    <i class="fab fa-google"></i>
                </a>

                <!-- Instagram -->
                <a class="btn btn-primary btn-floating m-1"
                   style="background-color: #ac2bac; "
                   href="https://www.instagram.com/solsis_gt/"
                   role="button">
                    <i class="fab fa-instagram"></i>
                </a>
                <!-- Github -->
                <a class="btn btn-primary btn-floating m-1"
                   style="background-color: #333333; "
                   href="https://github.com/SolsisGt"
                   role="button">
                    <i class="fab fa-github"></i>
                </a>
            </section>
            <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2022 Copyright:
            <a class="text-white text-decoration-none" href="http://solsis.rf.gd/?i=1"><img src="~/Images/LogoSolsis.png" height="40" width="30" />oluciones con Sistemas</a>
        </div>
        <!-- Copyright -->
    </footer>
    <script src="~/lib/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>